name: Deploy Workflow State to Novu

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "Bridge URL: ${{ secrets.NOVU_BRIDGE_URL }}"
          echo "Secret Key: ${{ secrets.NOVU_SECRET_KEY }}"
          echo "Ensure these match expected values."

      - name: Sync State to Novu
        uses: novuhq/actions-novu-sync@v2
        with:
          secret-key: ${{ secrets.NOVU_SECRET_KEY }}
          bridge-url: ${{ secrets.NOVU_BRIDGE_URL }}
